theme:
  active: "111, 0, 255"
  banner: "255, 30, 116" # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: Magenta # hovered pane border
  inactive: Gray # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: "111, 0, 255" # filled-in part of the progress bar
  playbar_progress_text: "111, 0, 255" # song length and time played/left indicator in the progress bar
  playbar_text: White # artist name in player pane
  selected: "255, 30, 116" # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "255, 255, 255" # text in panes
  header: White # header text in panes (e.g. 'Title', 'Artist', etc.)d